[Service]
  Host = "edgex-device-opc-ua"
  Port = 49952
  ConnectRetries = 3
  HealthCheck = ""
  Labels = [ "opc-ua" ]
  StartupMsg = "The opc-ua device service has started"
  ReadMaxLimit = 256
  Timeout = 5000
  CheckInterval = "10s"

[Clients]
  [Clients.Data]
    Host = "edgex-core-data"
    Port = 48080

  [Clients.Metadata]
    Host = "edgex-core-metadata"
    Port = 48081

[Device]
  DataTransform = true
  Discovery = false
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = ""
  SendReadingsOnChanged = true

[Logging]
  RemoteURL = ""
  File = "-"
  LogLevel = "WARNING"
